---
- name: "Block A1: Prepare Python Environment and Install Patroni"
  block:
    - name: "A1a. Create Python virtual environment for Patroni"
      ansible.builtin.command:
        cmd: python3 -m venv /opt/patroni-venv
        creates: /opt/patroni-venv/bin/activate

    - name: "A1b. Install Patroni and dependencies"
      ansible.builtin.pip:
        name:
          - patroni[etcd3]
          - psycopg2-binary
        virtualenv: /opt/patroni-venv
        virtualenv_command: /usr/bin/python3 -m venv

  rescue:
    - name: "Block A1: Prepare Python Environment and Install Patroni failed"
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result.msg | default('see task output above') }}"

- name: "Block A2: Stop and Disable default Postgres service"
  block:
    - name: "A2a. Ensure default postgresql service is stopped"
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
        enabled: false
      failed_when: false

  rescue:
    - name: "Block A2: Stop and Disable default Postgres service failed"
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result.msg | default('see task output above') }}"
