---
- name: "Section A. Setup Vault Environment"
  ansible.builtin.include_tasks: A-setup.yaml

- name: "Section B. Configure Vault Instance"
  ansible.builtin.include_tasks: B-configure.yaml

- name: "Section C. Initialize Vault Cluster"
  ansible.builtin.include_tasks: C-initialize.yaml
  when: inventory_hostname in groups['primary']

- name: "Section D. Unseal Vault Cluster"
  ansible.builtin.include_tasks: D-unseal.yaml
