---
- name: "Block E: Initialize Vault Cluster (Primary Only)"
  become: true
  run_once: true
  block:
    - name: "E1. Wait for Vault"
      ansible.builtin.wait_for:
        port: "{{ vault_port_api }}"
        delay: "{{ vault_wait_delay_seconds }}"

    - name: "E2. Initialize Vault"
      ansible.builtin.command: >
        vault operator init \
        -key-shares={{ vault_init_key_shares }} \
        -key-threshold={{ vault_init_key_threshold }} \
        -format=json
      environment:
        VAULT_ADDR: "https://127.0.0.1:{{ vault_port_api }}"
        VAULT_SKIP_VERIFY: "true"
      register: init_result
      changed_when: init_result.rc == 0
      ignore_errors: true

    - name: "E3. Fetch Administrative AppRole Credentials"
      community.hashi_vault.vault_kv2_get:
        url: "{{ dev_vault_url }}"
        engine_mount_point: "secret"
        path: "{{ dev_vault_api_path }}"
        validate_certs: false
      register: bootstrapper_creds
      delegate_to: localhost
      become: false

    - name: "E4. Set AppRole Credentials"
      ansible.builtin.set_fact:
        vault_approle_role_id: "{{ bootstrapper_creds.secret.role_id }}"
        vault_approle_secret_id: "{{ bootstrapper_creds.secret.secret_id }}"

    - name: "E5. Write Merged Secrets back to Vault"
      community.hashi_vault.vault_kv2_write:
        url: "{{ dev_vault_url }}"
        engine_mount_point: "secret"
        path: "{{ dev_vault_api_path }}"
        auth_method: "approle"
        role_id: "{{ vault_approle_role_id }}"
        secret_id: "{{ vault_approle_secret_id }}"
        validate_certs: false
        data:
          role_id: "{{ vault_approle_role_id }}"
          secret_id: "{{ vault_approle_secret_id }}"
          prod_vault_root_token: "{{ (init_result.stdout | from_json).root_token }}"
          prod_vault_unseal_keys: "{{ (init_result.stdout | from_json).unseal_keys_b64 }}"
      delegate_to: localhost
      become: false
      when: init_result.rc == 0
