---
- name: "Set loose-mode reverse path filtering and conntrack/bridge sysctls"
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - { name: "net.ipv4.conf.all.rp_filter", value: "2" }
    - { name: "net.ipv4.conf.default.rp_filter", value: "2" }
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.bridge.bridge-nf-call-iptables", value: "0" }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: "0" }
    - { name: "net.bridge.bridge-nf-call-arptables", value: "0" }
    - { name: "net.netfilter.nf_conntrack_max", value: "2097152" }
    - { name: "net.netfilter.nf_conntrack_tcp_be_liberal", value: "1" }
    - { name: "net.netfilter.nf_conntrack_tcp_timeout_time_wait", value: "30" }
