
# 1. Delivers CI signing key from Vault KV into a K8s Secret where Key is generated by init-secrets.sh
resource "kubernetes_manifest" "gitlab_ci_signing_key_eso" {
  count      = var.enable_ci_signing_key_rotation ? 1 : 0
  depends_on = [kubernetes_manifest.gitlab_vault_secret_store]

  manifest = {
    apiVersion = "external-secrets.io/v1"
    kind       = "ExternalSecret"
    metadata = {
      name      = "gitlab-ci-job-token-signing-key"
      namespace = kubernetes_namespace.gitlab_ns.metadata[0].name
    }
    spec = {
      refreshInterval = "1h"
      secretStoreRef = {
        name = "gitlab-vault-store"
        kind = "SecretStore"
      }
      target = {
        name           = "gitlab-ci-job-token-signing-key"
        creationPolicy = "Owner"
      }
      data = [
        {
          secretKey = "private_key.pem"
          remoteRef = {
            key      = "${data.terraform_remote_state.vault_pki.outputs.vault_kv_namespace}/gitlab/app/ci-job-token-signing-key"
            property = "private_key_pem"
          }
        }
      ]
    }
  }
}

# 2. Static GitLab Rails config for the rotation Job
resource "kubernetes_config_map" "ci_signing_job_gitlab_config" {
  count = var.enable_ci_signing_key_rotation ? 1 : 0

  metadata {
    name      = "gitlab-ci-signing-job-gitlab-cfg"
    namespace = kubernetes_namespace.gitlab_ns.metadata[0].name
  }

  data = {
    "gitlab.yml" = yamlencode({
      production = {
        gitlab = {
          host  = local.fqdn_gitlab
          https = true
          port  = 443
        }
        incoming_email = { enabled = false }
        extra          = {}
      }
    })
  }
}

# 3. Secret for database.yml which contains DB password and must not be a ConfigMap
resource "kubernetes_secret" "ci_signing_job_db_config" {
  count = var.enable_ci_signing_key_rotation ? 1 : 0

  metadata {
    name      = "gitlab-ci-signing-job-db-cfg"
    namespace = kubernetes_namespace.gitlab_ns.metadata[0].name
  }

  data = {
    "database.yml" = yamlencode({
      production = {
        adapter     = "postgresql"
        encoding    = "unicode"
        host        = local.fqdn_postgres
        port        = local.gitlab_db.port
        username    = local.gitlab_db.username
        database    = local.gitlab_db.database
        password    = local.gitlab_db.password
        sslmode     = "verify-ca"
        sslrootcert = "/tmp/ssl/ca.crt"
        sslcert     = "/tmp/ssl/tls.crt"
        sslkey      = "/tmp/ssl/tls.key"
      }
    })
  }
}

# 4. Overwrites ApplicationSetting with the Vault-sourced key
#    so Terraform creates a new Job resource rather than re-running the old one.
resource "kubernetes_job" "gitlab_ci_job_token_signing_key" {
  count = var.enable_ci_signing_key_rotation ? 1 : 0

  depends_on = [
    module.gitlab_core,
    kubernetes_manifest.gitlab_ci_signing_key_eso,
    kubernetes_secret.ci_signing_job_db_config,
    kubernetes_config_map.ci_signing_job_gitlab_config,
  ]

  metadata {
    name      = "gitlab-set-signing-key-${var.ci_signing_key_rotation_version}"
    namespace = kubernetes_namespace.gitlab_ns.metadata[0].name
  }

  spec {
    backoff_limit = 3

    template {
      metadata {}

      spec {
        restart_policy = "OnFailure"

        container {
          name  = "set-signing-key"
          image = "${local.gitlab_image_registry}/${local.gitlab_image_repository}/gitlab-toolbox-ce:${var.gitlab_version}"

          command = [
            "sh", "-c",
            <<-EOT
              set -e

              # Postgres TLS certs must be 0600 or the pg driver rejects them
              mkdir -p /tmp/ssl
              cp /etc/ssl/postgres/ca.crt  /tmp/ssl/ca.crt
              cp /etc/ssl/postgres/tls.crt /tmp/ssl/tls.crt
              cp /etc/ssl/postgres/tls.key /tmp/ssl/tls.key
              chmod 0600 /tmp/ssl/tls.key

              gitlab-rails runner "
                key = File.read('/mnt/signing-key/private_key.pem').strip
                ApplicationSetting.current_without_cache.update!(ci_job_token_signing_key: key)
                ApplicationSetting.expire
                present = ApplicationSetting.current.ci_job_token_signing_key.present?
                puts 'ci_job_token_signing_key set: ' + present.to_s
                exit 1 unless present
              "
            EOT
          ]

          volume_mount {
            name       = "postgres-tls"
            mount_path = "/etc/ssl/postgres"
            read_only  = true
          }

          volume_mount {
            name       = "signing-key"
            mount_path = "/mnt/signing-key"
            read_only  = true
          }

          volume_mount {
            name       = "db-config"
            mount_path = "/srv/gitlab/config/database.yml"
            sub_path   = "database.yml"
            read_only  = true
          }

          volume_mount {
            name       = "gitlab-config"
            mount_path = "/srv/gitlab/config/gitlab.yml"
            sub_path   = "gitlab.yml"
            read_only  = true
          }

          volume_mount {
            name       = "rails-secrets"
            mount_path = "/srv/gitlab/config/secrets.yml"
            sub_path   = "secrets.yml"
            read_only  = true
          }
        }

        volume {
          name = "postgres-tls"
          secret { secret_name = "gitlab-postgres-tls" }
        }

        # ESO-managed secret; name is the ExternalSecret target.name
        volume {
          name = "signing-key"
          secret { secret_name = "gitlab-ci-job-token-signing-key" }
        }

        volume {
          name = "db-config"
          secret {
            secret_name = kubernetes_secret.ci_signing_job_db_config[0].metadata[0].name
          }
        }

        volume {
          name = "gitlab-config"
          config_map {
            name = kubernetes_config_map.ci_signing_job_gitlab_config[0].metadata[0].name
          }
        }

        # ESO-managed secret; name matches ExternalSecret target.name in resources-gitlab-rails-secrets.tf
        volume {
          name = "rails-secrets"
          secret { secret_name = "gitlab-rails-secret" }
        }
      }
    }
  }

  wait_for_completion = true

  timeouts {
    create = "15m"
  }
}
