---
- name: "Block B1: Configure and Start"
  become: true
  block:
    - name: "B1a. Configure Vault using Raft"
      ansible.builtin.template:
        src: vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: "0644"
      notify: Restart Vault Service

    - name: "B1b. Start and Enable Vault Service"
      ansible.builtin.systemd:
        name: vault
        state: started
        enabled: true

  rescue:
    - name: "Block B1: Configure and Start failed"
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result.msg | default('see task output above') }}"

- name: "B2. Flush Handlers (Restart Vault Service)"
  ansible.builtin.meta: flush_handlers
