---
- name: "B1. Create MinIO environment file"
  ansible.builtin.template:
    src: minio-default.j2
    dest: /etc/default/minio
    owner: root
    group: root
    mode: "0600"
  notify: Restart MinIO

