---
- name: "Section A. Setup MinIO Environment"
  ansible.builtin.include_tasks: A-setup.yaml

- name: "Section B. Configure Network Routing (R81)"
  ansible.builtin.include_role:
    name: 81-asymmetric-routing
  vars:
    routing_static_routes:
      - to: "{{ minio_static_route_to }}"
        via: "{{ minio_static_route_via }}"
        metric: "{{ minio_static_route_metric }}"
  when: minio_static_route_to is defined

- name: "Section C. Configure MinIO Instance"
  ansible.builtin.include_tasks: B-configure.yaml

- name: "Section D. Manage MinIO Service"
  ansible.builtin.include_tasks: C-service.yaml

- name: "Section E. Verify MinIO Cluster"
  ansible.builtin.include_tasks: D-verification.yaml
