---
- name: "Section A. Setup MinIO Environment"
  ansible.builtin.include_tasks: A-setup.yaml

- name: "Section B. Configure Network Routing"
  ansible.builtin.include_role:
    name: 81-asymmetric-routing
  vars:
    routing_static_routes:
      - to: "{{ minio_static_route_to }}"
        via: "{{ minio_static_route_via }}"
        metric: "{{ minio_static_route_metric }}"
  when: minio_static_route_to is defined

- name: "Section C. Configure MinIO Instance"
  ansible.builtin.include_tasks: B-configure.yaml

- name: "Section D. Prepare Environment for Vault Agent"
  ansible.builtin.include_role:
    name: 82-vault-agent
  vars:
    vault_agent_owner: "{{ minio_user }}"
    vault_agent_group: "{{ minio_group }}"
    vault_agent_cert_base_dir: "/etc/minio/certs"
    vault_agent_cert_dirs:
      - "/etc/minio/certs"
      - "/etc/minio/certs/CAs"
    vault_agent_cert_name: "public.crt"
    vault_agent_key_name: "private.key"
    vault_agent_ca_name: "CAs/root_ca.crt"
    vault_agent_wait_file: "/etc/minio/certs/public.crt"
    vault_agent_post_command: "systemctl restart minio"
    vault_agent_ip_sans: "{{ advertise_ip }},{{ minio_ha_virtual_ip }}"

- name: "Section E. Manage MinIO Service"
  ansible.builtin.include_tasks: C-service.yaml

- name: "Section E. Verify MinIO Cluster"
  ansible.builtin.include_tasks: D-verification.yaml
