---
- name: "Role 81: Configure Network Routing"
  ansible.builtin.include_role:
    name: 81-utils-asymmetric-routing
  vars:
    routing_static_routes:
      - to: "{{ microk8s_static_route_to }}"
        via: "{{ microk8s_static_route_via }}"
        metric: "{{ microk8s_static_route_metric }}"
  when: microk8s_static_route_to is defined

- name: "Section A. Setup MicroK8s Prerequisites"
  ansible.builtin.include_tasks: B-prerequisites.yaml

- name: "Section B. Cleanup and Prepare Nodes"
  ansible.builtin.include_tasks: C-nodes.yaml

- name: "Section C. Configure High Availability (Replicas)"
  ansible.builtin.include_tasks: D-high-availability.yaml
  when: inventory_hostname in (groups['replica'] | default([]))

- name: "Section D. Configure Addons (Primary)"
  ansible.builtin.include_tasks: E-addons.yaml
  when: inventory_hostname in (groups['primary'] | default([]))

- name: "Section E. Setup Kubeconfig"
  ansible.builtin.include_tasks: F-kubeconfig.yaml
