---
- name: "Gather service facts"
  ansible.builtin.service_facts:

- name: "Minimal: Stop and Mask unnecessary services (Keep binaries)"
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  loop:
    # Snapd only MicroK8s will unmask/enable this explicitly
    - snapd.service
    - snapd.socket
    - snapd.seeded.service

    # Storage is not needed for KVM qcow2 since Multipath is for SAN/FibreChannel
    - multipathd.service
    - multipathd.socket

    # Auto-Updates is dangerous for Immutable Infra
    - unattended-upgrades.service

    # Desktop/Hardware Integrations are useless in Headless VM
    - accounts-daemon.service
    - ModemManager.service
    - udisks2.service
    - switcheroo-control.service

    # Ubuntu Specific Ads/Telemetry
    - ua-timer.timer
    - ua-timer.service
    - motd-news.timer
    - motd-news.service
  when: >
    item in ansible_facts.services or
    item ~ '.service' in ansible_facts.services or
    item | regex_replace('\.service$', '') in ansible_facts.services

# dbus-activates packagekit is installed by the gitlab-ce package during dpkg configuration,
# which makes that masked unit activation fail with UnitMasked
- name: "Minimal: Stop and disable packagekit without masking"
  become: true
  ansible.builtin.systemd:
    name: packagekit.service
    state: stopped
    enabled: false
    masked: false
  when: "'packagekit.service' in ansible_facts.services"
