---
- name: "Block D1: Generate and register cluster join parameters"
  block:
    - name: "D1a. Check if admin.conf exists on the primary master"
      ansible.builtin.stat:
        path: "/etc/kubernetes/admin.conf"
      register: kubeconfig

    - name: "D1b. Assert that kubeadm init was successful before proceeding"
      ansible.builtin.assert:
        that: kubeconfig.stat.exists
        fail_msg: >-
          Cannot generate join parameters because kubeadm init seems to have failed
          (/etc/kubernetes/admin.conf not found).

    - name: "D1c. Create a new token"
      ansible.builtin.command:
        cmd: "kubeadm token create"
      register: kubeadm_token_result
      changed_when: kubeadm_token_result.rc == 0

    - name: "D1d. Get the CA certificate hash"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
          openssl rsa -pubin -outform der 2>/dev/null |
          openssl dgst -sha256 -hex | sed 's/^.* //'
        executable: /bin/bash
      register: kubeadm_ca_hash_result
      changed_when: false

    - name: "D1e. Upload certs and get the certificate key"
      ansible.builtin.command:
        cmd: "kubeadm init phase upload-certs --upload-certs"
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      register: cert_key_result
      changed_when: "'certificate key' in cert_key_result.stdout"

    - name: "D1f. Register join parameters as facts"
      ansible.builtin.set_fact:
        kubeadm_token: "{{ kubeadm_token_result.stdout }}"
        kubeadm_ca_hash: "{{ kubeadm_ca_hash_result.stdout }}"
        kubeadm_cert_key: "{{ cert_key_result.stdout_lines | last }}"
        cacheable: true

  rescue:
    - name: "Block D1: Generate and register cluster join parameters failed"
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result.msg | default('see task output above') }}"
