---
- name: "Section A. Setup Redis Environment"
  ansible.builtin.include_tasks: A-setup.yaml

- name: "Role 81: Configure Network Routing"
  ansible.builtin.include_role:
    name: 81-utils-asymmetric-routing
  vars:
    routing_static_routes:
      - to: "{{ redis_static_route_to }}"
        via: "{{ redis_static_route_via }}"
        metric: "{{ redis_static_route_metric }}"
  when: redis_static_route_to is defined

- name: "Section B. Configure Redis Instance"
  ansible.builtin.include_tasks: B-configure.yaml

- name: "Role 82: Prepare Environment for Vault Agent"
  ansible.builtin.include_role:
    name: 82-utils-vault-agent
  vars:
    vault_agent_owner: "{{ redis_user }}"
    vault_agent_group: "{{ redis_group }}"
    vault_agent_cert_base_dir: "/etc/redis/certs"
    vault_agent_post_command: "systemctl restart redis-server redis-sentinel"
    vault_agent_ip_sans: "{{ advertise_ip }},{{ redis_ha_virtual_ip }}"

- name: "Section C. Manage Redis Services"
  ansible.builtin.include_tasks: C-service.yaml
