---
- name: "B1. Create Redis server configuration"
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: "0640"
  notify: Restart redis-server

- name: "B2. Create Redis Sentinel configuration"
  ansible.builtin.template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    owner: redis
    group: redis
    mode: "0640"
  notify: Restart redis-sentinel
