---
- name: "Play: Operation - Unseal All Vault Nodes"
  hosts: primary, replica
  become: true
  gather_facts: true
  tasks:
    - name: "Execute Vault Unseal only"
      ansible.builtin.include_role:
        name: 15-vault
        tasks_from: D-unseal.yaml
