---
- name: "PoC: Single Node Redis Configuration"
  hosts: all
  become: true
  pre_tasks:
    - name: "PoC: Restore complex variables from JSON strings"
      set_fact:
        redis_static_routes: "{{ redis_static_routes_json_raw | from_json }}"
      when: redis_static_routes_json_raw is defined

    - name: "PoC: Restore cluster IPs from JSON"
      set_fact:
        redis_cluster_ips: "{{ redis_cluster_ips_json_raw | from_json }}"
      when: redis_cluster_ips_json_raw is defined

  roles:
    - 26-redis-sentinel
