---
- name: Restart Service
  ansible.builtin.command:
    cmd: "gitlab-ctl restart {{ node_role }}"
  changed_when: false

- name: Update system CA certificates
  ansible.builtin.command:
    cmd: update-ca-certificates
  changed_when: true
