---
# Harbor Installation Paths
harbor_install_dir: "/opt/harbor-install"
harbor_data_dir: "/data/harbor"

# PKI Paths (Host Side)
# Vault Agent will write certs here.
# Harbor will mount these files into the container.
harbor_pki_dir: "{{ harbor_data_dir }}/pki"
harbor_cert_path: "{{ harbor_pki_dir }}/server.crt"
harbor_key_path: "{{ harbor_pki_dir }}/server.key"
harbor_ca_path: "{{ harbor_pki_dir }}/ca.crt"

# Internal Harbor Config PKI Paths (for Nginx)
harbor_config_cert_dir: "{{ harbor_data_dir }}/secret/cert"

# Vault Agent Configuration
vault_agent_config_dir: "/etc/vault.d"

# Database and Harbor Admin Password from Vault
harbor_bootstrapper_admin_password: "{{ harbor_vault_secrets.secret.harbor_bootstrapper_admin_password }}"
harbor_bootstrapper_pg_db_password: "{{ harbor_vault_secrets.secret.harbor_bootstrapper_pg_db_password }}"

# Helm Installation
helm_version: "v3.14.3"
helm_install_script_url: "https://raw.githubusercontent.com/helm/helm/{{ helm_version }}/scripts/get-helm-3"
helm_install_script_checksum: "sha256:6701e269a95eec0a5f67067f504f43ad94e9b4a52ec1205d26b3973d6f5cb3dc"
