---
# Section B: Configuration
vault_ui_enabled: true
vault_disable_mlock: true # Set to true to avoid memory locking issues

# Section C: Initialization
vault_init_key_shares: 1
vault_init_key_threshold: 1
vault_wait_delay_seconds: 10

# Section D: Unseal
vault_unseal_retries: 24
vault_unseal_delay_seconds: 5
